[workspace]
members = [
    "crates/*",
]
resolver = "2"

[workspace.package]
version = "0.6.0"
authors = ["Sebastian Beyvers <sb@pus.de>"]
edition = "2021"
repository = "https://github.com/ArunaStorage/aruna-file"
license = "MIT OR Apache-2.0"