[package]
name = "pithos"
description = "CLI for the Pithos container file format"
version = "0.8.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = ["crates-io"]
include = [
    "src/**/*.rs",
    "README.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
pithos_lib = { version = "0.8.0", path = "../pithos_lib" }
thiserror = { workspace = true }
tracing.workspace = true
tracing-subscriber.workspace = true
zeroize = "1.8.2"
rustix = { version = "1.1.4", features = ["fs"] }
#indicatif = "0.17.9"

[dev-dependencies]
fastcdc = "4.0.1"
