[package]
name = "pithos_pyo3"
description = "Unpublished, nonfunctional stub reserved for a possible future Python binding"
version = "0.8.0"
publish = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
pithos_lib = { version = "0.8.0", path = "../pithos_lib" }
